name: Deploy to Cloudfare pages 
run: | 
curl -X POST "https://api.cloudfare.com/client/v4/page/user/tokens/verify"\ 
     -H "Authorization: Bearer DyIn5JKVfacBSQqDE8X-VpSKDTdNLsEA0yIsvgdr"\ 
     -H "Content-type: application/json" -d '"deploy:" "source:" "./"' 
     env: "https://api.cloudfare.com/client/v4/page/user/tokens/verify"\:{{"DyIn5JKVfacBSQqDE8X-VpSKDTdNLsEA0yIsvgdr"\}}
    
